# Generated by Django 4.2.3 on 2023-07-22 15:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('task_title', models.CharField(max_length=100)),
                ('task_description', models.CharField(blank=True, max_length=300, null=True)),
                ('is_important', models.BooleanField(default=False)),
                ('task_completed', models.BooleanField(default=False)),
                ('task_created_at', models.DateTimeField(auto_now_add=True)),
                ('task_updated_at', models.DateTimeField(auto_now=True)),
                ('task_due_date', models.DateTimeField(default=datetime.datetime(2023, 7, 23, 21, 24, 2, 633193))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
